package com.steamedbunx.android.normalizedsearchdemo

fun getPhraseBank(): List<String> {
    return listOf(
        "cull",
        "doran's blade",
        "doran's ring",
        "doran's shield",
        "guardian's hammer",
        "guardian's horn",
        "guardian's orb",
        "control ward",
        "corruption potion",
        "elixir of iron",
        "elixir of sorcery",
        "elixir of wrath",
        "entropy field",
        "espresso snax",
        "flash zone",
        "frosted snax",
        "health potion",
        "oracle's extract",
        "port pad",
        "rainbow snax party pack!",
        "refillable potion",
        "shield totem",
        "siege ballista",
        "super spicy snax",
        "tower: beam of ruination",
        "tower: storm bulwark",
        "vanguard banner",
        "arcane sweeper",
        "farsight alteration",
        "golden transcendence",
        "oracle lens",
        "seer stone",
        "siege sight warder",
        "warding totem",
        "black spear",
        "cloak of stars",
        "cosmic shackle",
        "dark matter scythe",
        "dark star sigil",
        "elixir of skill",
        "eye of the herald",
        "gravity boots",
        "looted oracle's extract",
        "mana potion",
        "minion dematerializer",
        "peering farsight ward",
        "pilfered health potion"
    )
}